# Generated by Django 5.1.1 on 2024-09-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_item_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemEntry',
        ),
    ]
